services:
  # 后端 API 服务
  - type: web
    name: temple-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python main.py"
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false  # 需要在 Render 控制台手动设置
      - key: SERVER_HOST
        value: "0.0.0.0"
      - key: SERVER_PORT
        value: "10000"  # Render 默认端口
      - key: DEBUG
        value: "False"
    
  # 前端 Web 应用
  - type: web
    name: temple-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm start"
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false  # 需要在 Render 控制台手动设置后端 URL
      - key: NODE_ENV
        value: "production"